=== Omnia-ELmasry/ChatApplication/JAVAClientChatMVC/src/clientchat/messageParser/MsgOutput.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/MsgOutput.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE msgRoot SYSTEM "MsgOutput.dtd">

    <msgRoot>
    ...
    </msgRoot>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT msgRoot (header|msgElement)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT header (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT msgElement (body|to)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT body (content|date|from)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT content (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT date (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT from (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT to (#PCDATA)>

=== Omnia-ELmasry/ChatApplication/JAVAClientChatMVC/src/clientchat/messageParser/MsgOutput.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='Message.xsl'?>
<!DOCTYPE msgRoot SYSTEM 'MsgOutput.dtd'>
<msgRoot>
    <header>Msg Header</header>
    <msgElement>
        <body>
            <content>fdsfdffddddddddddd</content>
            <date>6 Feb 2017 11:59:29 GMT</date>
            <from>me</from>
        </body>
        <body>
            <content>dddddddddddddd</content>
            <date>6 Feb 2017 11:59:31 GMT</date>
            <from>me</from>
        </body>
        <body>
            <content>dddddvvvvvvvvvvvvv</content>
            <date>6 Feb 2017 11:59:35 GMT</date>
            <from>yousef says :&lt;br&gt;</from>
        </body>
        <to>To XYZ</to>
    </msgElement>
</msgRoot>
